[package]
name = "collada-io"
version = "0.1.0"
authors = ["Matthew Henderson <mattw2018@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
RustyXML = "0.3.0"